name: Go get lnd

on: push

jobs:
  go-get:
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        way:
          - go-get
          - go-build

        go:
          - 1.12
          - 1.13

        lnd:
          - v0.7.1-beta
          - v0.7.0-beta
          - v0.6.1-beta
          - v0.6.0-beta

    steps:
      - uses: actions/checkout@v1.0.0

      - name: Build
        run: |
          DIR='.'

          if [[ "${{ matrix.way }}" != 'go-get' ]]; then
            DIR='src/'
          fi

          docker build . \
            --build-arg "GOVER=${{ matrix.go }}" \
            --build-arg "LNDVER=${{ matrix.lnd }}"

