on: push

jobs:
  build:
    name: Attempt to go-get lnd
    runs-on: ubuntu-18.04
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.11
          - 1.12
          - 1.13

    steps:
      - uses: actions/checkout@v1.0.0

      - run: docker build --build-arg "GOVER=${{ matrix.go }}" .
